"""empty message

Revision ID: 35f97800fae8
Revises: 7c9b690c3f78
Create Date: 2018-06-27 01:10:40.580621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35f97800fae8'
down_revision = '7c9b690c3f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_credential')
    op.drop_table('users')
    op.drop_index('ix_login_credential_email', table_name='login_credential')
    op.drop_index('ix_login_credential_notes', table_name='login_credential')
    op.drop_index('ix_login_credential_service', table_name='login_credential')
    op.drop_index('ix_login_credential_username', table_name='login_credential')
    op.drop_table('login_credential')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('login_credential',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], name='login_credential_category_fkey'),
    sa.PrimaryKeyConstraint('id', name='login_credential_pkey')
    )
    op.create_index('ix_login_credential_username', 'login_credential', ['username'], unique=False)
    op.create_index('ix_login_credential_service', 'login_credential', ['service'], unique=False)
    op.create_index('ix_login_credential_notes', 'login_credential', ['notes'], unique=False)
    op.create_index('ix_login_credential_email', 'login_credential', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('_master', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('wallet_credential',
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='wallet_credential_pkey')
    )
    # ### end Alembic commands ###
