"""f

Revision ID: 7a0be095de50
Revises: 
Create Date: 2018-07-10 15:08:56.813837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0be095de50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('file_record_id', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('password_record_id', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('wallet_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'file_records', ['file_record_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'password_records', ['password_record_id'], ['id'])
    op.create_foreign_key(None, 'tags', 'wallet_records', ['wallet_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'wallet_record_id')
    op.drop_column('tags', 'password_record_id')
    op.drop_column('tags', 'file_record_id')
    # ### end Alembic commands ###
