"""empty message

Revision ID: dd566f63d244
Revises: 9e89b2209417
Create Date: 2018-07-03 15:34:30.677431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd566f63d244'
down_revision = '9e89b2209417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('category_name', sa.String(length=128), nullable=False))
    op.drop_column('categories', 'id')
    op.drop_column('categories', 'name')
    op.add_column('site_records', sa.Column('owner_id', sa.String(length=32), nullable=False))
    op.drop_column('site_records', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_records', sa.Column('owner', sa.VARCHAR(length=32), nullable=False))
    op.drop_column('site_records', 'owner_id')
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=128), nullable=False))
    op.add_column('categories', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('categories', 'category_name')
    op.drop_column('categories', 'category_id')
    # ### end Alembic commands ###
